language: node_js
node_js:
  - '10'
sudo: required
addons:
  chrome: stable
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
